version: "3.1"
services:

  front:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tet-bookstore.tk:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/tet-bookstore.tk/fullchain.pem:/etc/letsencrypt/live/tet-bookstore.tk/fullchain.pem
      - /etc/letsencrypt/live/tet-bookstore.tk/privkey.pem:/etc/letsencrypt/live/tet-bookstore.tk/privkey.pem
      - /usr/share/nginx/html/bookstore:/usr/share/nginx/html/bookstore

volumes:
  front: